//go:build !ignore_autogenerated

/*
Copyright 2025-2026 The llm-d Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CountForLauncher) DeepCopyInto(out *CountForLauncher) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CountForLauncher.
func (in *CountForLauncher) DeepCopy() *CountForLauncher {
	if in == nil {
		return nil
	}
	out := new(CountForLauncher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddedObjectMeta) DeepCopyInto(out *EmbeddedObjectMeta) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddedObjectMeta.
func (in *EmbeddedObjectMeta) DeepCopy() *EmbeddedObjectMeta {
	if in == nil {
		return nil
	}
	out := new(EmbeddedObjectMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddedPodTemplateSpec) DeepCopyInto(out *EmbeddedPodTemplateSpec) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddedPodTemplateSpec.
func (in *EmbeddedPodTemplateSpec) DeepCopy() *EmbeddedPodTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(EmbeddedPodTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnhancedNodeSelector) DeepCopyInto(out *EnhancedNodeSelector) {
	*out = *in
	in.LabelSelector.DeepCopyInto(&out.LabelSelector)
	if in.AllocatableResources != nil {
		in, out := &in.AllocatableResources, &out.AllocatableResources
		*out = make(ResourceRanges, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnhancedNodeSelector.
func (in *EnhancedNodeSelector) DeepCopy() *EnhancedNodeSelector {
	if in == nil {
		return nil
	}
	out := new(EnhancedNodeSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceServerConfig) DeepCopyInto(out *InferenceServerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceServerConfig.
func (in *InferenceServerConfig) DeepCopy() *InferenceServerConfig {
	if in == nil {
		return nil
	}
	out := new(InferenceServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferenceServerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceServerConfigList) DeepCopyInto(out *InferenceServerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InferenceServerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceServerConfigList.
func (in *InferenceServerConfigList) DeepCopy() *InferenceServerConfigList {
	if in == nil {
		return nil
	}
	out := new(InferenceServerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferenceServerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceServerConfigSpec) DeepCopyInto(out *InferenceServerConfigSpec) {
	*out = *in
	in.ModelServerConfig.DeepCopyInto(&out.ModelServerConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceServerConfigSpec.
func (in *InferenceServerConfigSpec) DeepCopy() *InferenceServerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(InferenceServerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceServerConfigStatus) DeepCopyInto(out *InferenceServerConfigStatus) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceServerConfigStatus.
func (in *InferenceServerConfigStatus) DeepCopy() *InferenceServerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(InferenceServerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LauncherConfig) DeepCopyInto(out *LauncherConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LauncherConfig.
func (in *LauncherConfig) DeepCopy() *LauncherConfig {
	if in == nil {
		return nil
	}
	out := new(LauncherConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LauncherConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LauncherConfigList) DeepCopyInto(out *LauncherConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LauncherConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LauncherConfigList.
func (in *LauncherConfigList) DeepCopy() *LauncherConfigList {
	if in == nil {
		return nil
	}
	out := new(LauncherConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LauncherConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LauncherConfigSpec) DeepCopyInto(out *LauncherConfigSpec) {
	*out = *in
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LauncherConfigSpec.
func (in *LauncherConfigSpec) DeepCopy() *LauncherConfigSpec {
	if in == nil {
		return nil
	}
	out := new(LauncherConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LauncherConfigStatus) DeepCopyInto(out *LauncherConfigStatus) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LauncherConfigStatus.
func (in *LauncherConfigStatus) DeepCopy() *LauncherConfigStatus {
	if in == nil {
		return nil
	}
	out := new(LauncherConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LauncherPopulationPolicy) DeepCopyInto(out *LauncherPopulationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LauncherPopulationPolicy.
func (in *LauncherPopulationPolicy) DeepCopy() *LauncherPopulationPolicy {
	if in == nil {
		return nil
	}
	out := new(LauncherPopulationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LauncherPopulationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LauncherPopulationPolicyList) DeepCopyInto(out *LauncherPopulationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LauncherPopulationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LauncherPopulationPolicyList.
func (in *LauncherPopulationPolicyList) DeepCopy() *LauncherPopulationPolicyList {
	if in == nil {
		return nil
	}
	out := new(LauncherPopulationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LauncherPopulationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LauncherPopulationPolicySpec) DeepCopyInto(out *LauncherPopulationPolicySpec) {
	*out = *in
	in.EnhancedNodeSelector.DeepCopyInto(&out.EnhancedNodeSelector)
	if in.CountForLauncher != nil {
		in, out := &in.CountForLauncher, &out.CountForLauncher
		*out = make([]CountForLauncher, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LauncherPopulationPolicySpec.
func (in *LauncherPopulationPolicySpec) DeepCopy() *LauncherPopulationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(LauncherPopulationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LauncherPopulationPolicyStatus) DeepCopyInto(out *LauncherPopulationPolicyStatus) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LauncherPopulationPolicyStatus.
func (in *LauncherPopulationPolicyStatus) DeepCopy() *LauncherPopulationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(LauncherPopulationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelServerConfig) DeepCopyInto(out *ModelServerConfig) {
	*out = *in
	if in.EnvVars != nil {
		in, out := &in.EnvVars, &out.EnvVars
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelServerConfig.
func (in *ModelServerConfig) DeepCopy() *ModelServerConfig {
	if in == nil {
		return nil
	}
	out := new(ModelServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRange) DeepCopyInto(out *ResourceRange) {
	*out = *in
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRange.
func (in *ResourceRange) DeepCopy() *ResourceRange {
	if in == nil {
		return nil
	}
	out := new(ResourceRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ResourceRanges) DeepCopyInto(out *ResourceRanges) {
	{
		in := &in
		*out = make(ResourceRanges, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRanges.
func (in ResourceRanges) DeepCopy() ResourceRanges {
	if in == nil {
		return nil
	}
	out := new(ResourceRanges)
	in.DeepCopyInto(out)
	return *out
}
